version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bukken_quiz_db 
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: bukken_quiz_web 
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  # ホストのappディレクトリをマウント
    depends_on:
      - db
    env_file:
      - .env  # ← .env を使う
    # コンテナ起動時にDjangoプロジェクトを生成（既存でない場合）
    command: >
        daphne -b 0.0.0.0 -p 8000 bukken_quiz_web.asgi:application

volumes:
  db_data:
